-- 028 RBAC
CREATE TABLE IF NOT EXISTS rbac_roles (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, description TEXT, is_system INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS rbac_permissions (id TEXT PRIMARY KEY, resource TEXT NOT NULL, action TEXT NOT NULL, resource_id TEXT, CONSTRAINT uniq_permission UNIQUE (resource, action, resource_id));
CREATE TABLE IF NOT EXISTS rbac_role_permissions (role_id TEXT NOT NULL, permission_id TEXT NOT NULL, PRIMARY KEY (role_id, permission_id));
CREATE TABLE IF NOT EXISTS rbac_user_roles (user_id TEXT NOT NULL, role_id TEXT NOT NULL, workspace_id TEXT, assigned_at INTEGER NOT NULL, PRIMARY KEY (user_id, role_id, workspace_id));
CREATE INDEX IF NOT EXISTS idx_rbac_ur_user ON rbac_user_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_rbac_ur_role ON rbac_user_roles(role_id);
INSERT OR IGNORE INTO rbac_roles (id, name, description, is_system) VALUES ('role-admin', 'admin', 'Full access', 1), ('role-editor', 'editor', 'Create/edit', 1), ('role-operator', 'operator', 'Execute', 1), ('role-viewer', 'viewer', 'Read-only', 1), ('role-auditor', 'auditor', 'Read+audit', 1);
INSERT OR IGNORE INTO rbac_permissions (id, resource, action) VALUES ('perm-workflow-create', 'workflow', 'create'), ('perm-workflow-read', 'workflow', 'read'), ('perm-workflow-execute', 'workflow', 'execute'), ('perm-workflow-delete', 'workflow', 'delete'), ('perm-agent-create', 'agent', 'create'), ('perm-agent-read', 'agent', 'read'), ('perm-agent-execute', 'agent', 'execute'), ('perm-kb-read', 'kb', 'read'), ('perm-kb-write', 'kb', 'write'), ('perm-tool-execute', 'tool', 'execute'), ('perm-tool-approve', 'tool', 'approve'), ('perm-compliance-export', 'compliance', 'export'), ('perm-audit-read', 'audit', 'read'), ('perm-user-manage', 'user', 'manage');
INSERT OR IGNORE INTO rbac_role_permissions (role_id, permission_id) SELECT 'role-admin', id FROM rbac_permissions;
INSERT OR IGNORE INTO rbac_role_permissions (role_id, permission_id) VALUES ('role-editor', 'perm-workflow-create'), ('role-editor', 'perm-workflow-read'), ('role-editor', 'perm-workflow-execute'), ('role-editor', 'perm-agent-create'), ('role-editor', 'perm-agent-read'), ('role-editor', 'perm-agent-execute'), ('role-editor', 'perm-kb-read'), ('role-editor', 'perm-kb-write'), ('role-editor', 'perm-tool-execute');
INSERT OR IGNORE INTO rbac_role_permissions (role_id, permission_id) VALUES ('role-operator', 'perm-workflow-read'), ('role-operator', 'perm-workflow-execute'), ('role-operator', 'perm-agent-read'), ('role-operator', 'perm-agent-execute'), ('role-operator', 'perm-kb-read'), ('role-operator', 'perm-tool-execute');
INSERT OR IGNORE INTO rbac_role_permissions (role_id, permission_id) VALUES ('role-viewer', 'perm-workflow-read'), ('role-viewer', 'perm-agent-read'), ('role-viewer', 'perm-kb-read');
INSERT OR IGNORE INTO rbac_role_permissions (role_id, permission_id) VALUES ('role-auditor', 'perm-workflow-read'), ('role-auditor', 'perm-agent-read'), ('role-auditor', 'perm-kb-read'), ('role-auditor', 'perm-audit-read'), ('role-auditor', 'perm-compliance-export');
