[package]
name = "maple-agent"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
dashmap = { workspace = true }
sqlx = { workspace = true }
maple-llm = { workspace = true }
maple-engine = { workspace = true }
maple-kb = { workspace = true }
futures = { workspace = true }
maple-macro = { workspace = true }
tokio-util = { workspace = true }
